//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRDapp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_hsc
    {
        public int hsc_id { get; set; }
        public Nullable<double> hsc_precentage { get; set; }
        public string hsc_institue { get; set; }
        public string hsc_doc { get; set; }
        public Nullable<int> hsc_fk_ap_id { get; set; }
    
        public virtual tbl_applicant_personal tbl_applicant_personal { get; set; }
    }
}
