//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRDapp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_applicant_personal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_applicant_personal()
        {
            this.tbl_grad = new HashSet<tbl_grad>();
            this.tbl_hsc = new HashSet<tbl_hsc>();
            this.tbl_mas = new HashSet<tbl_mas>();
            this.tbl_ssc = new HashSet<tbl_ssc>();
        }
    
        public int ap_id { get; set; }
        public string ap_name { get; set; }
        public string ap_position { get; set; }
        public string ap_phone1 { get; set; }
        public string ap_phone2 { get; set; }
        public string ap_email { get; set; }
        public string ap_image { get; set; }
        public Nullable<int> ap_gender { get; set; }
        public Nullable<System.DateTime> ap_dob { get; set; }
        public string ap_salary { get; set; }
        public string ap_password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_grad> tbl_grad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_hsc> tbl_hsc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_mas> tbl_mas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ssc> tbl_ssc { get; set; }
    }
}
